server:
  port: 9090
  servlet:
    context-path: /upload-service/v1
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/upload_service?useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect