server:
  port: 5654

spring:
 datasource:
   url: jdbc:mysql://localhost:3306/extract_csv?useTimezone=true&serverTimezone=UTC
   username: root
   password: admin
   driver-class-name: com.mysql.cj.jdbc.Driver
 jpa:
   hibernate:
     ddl-auto: update
   properties:
     hibernate:
       dialect: org.hibernate.dialect.MySQL5Dialect